version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: Build application
          command: |
            # Add build commands here

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test